Portfolio
Najeeba-Qarqin/Portfolio-JS pull request #1
Opened 2024-07-24 19:29 UTC by Najeeba-Qarqin

Portfolio project created in HTML, CSS and JavaScript and designed by UI/UX designers.

2024-07-27 20:56 UTC, Najeeba-Qarqin commented
Hi @Hasinarahman👋 
Please review my project.

2024-07-28 17:59 UTC, Hasinarahman commented
Hi @Najeeba-Qarqin  🙋‍♀️,
Highlights 🌞
🎉 Great Design Implemented
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Personal Portfolio project equirments
✔️ You have followed the all design of figma from UX/UI student
✔️ all of your links works good
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a README.md file

just one thing to say your view button of the certificate is so close to the another certificate please give some space on design it.

2024-07-28 19:08 UTC, Najeeba-Qarqin commented
Hi @Hasinarahman 
Thank you for your feedback!
I'll implement them.

2024-07-28 19:13 UTC, Najeeba-Qarqin commented
@Hasinarahman I implemented your feedback please review again.

2024-07-29 18:53 UTC, ahzamir commented
@Najeeba-Qarqin 

- Well done Najeeba, your project is almost done but has some minor issues first of all before I check your project design and functionality, I need to match it with the Figma design so please provide the link to the Figma design in reply to this message and also on your README.md file.

2024-07-29 19:27 UTC, ahzamir requested changes
Hey @Najeeba-Qarqin , Well done and great job by implementing most of the requirements:

- Well done your project's functionality almost meets most of the requirements, but still your project has some minor issues you need to work on.

- This review and feedback is just for your project's README.md, HTML, and JavaScript requirements. In order to get feedback and review for your design you have to provide link of the Figma design on your readme file.

2024-07-29 19:27 UTC, ahzamir commented on script.js
> +    { name: 'JavaScript', link: 'www.com', image: './images/JS.png' },
- Add the actual link to your certifications.

2024-07-29 19:27 UTC, ahzamir commented on script.js
> +    liveLink: 'https://najeeba-qarqin.github.io/Prtfolio',
- This link is broken and not working

2024-07-29 19:27 UTC, ahzamir commented on script.js
> +    liveLink: 'https://najeeba-qarqin.github.io/Prtfolio',
- This link is broken, please add the actual live link for this project.

2024-07-29 19:27 UTC, ahzamir commented on index.html
> +      <form action="" name="myform" class="myform flex" id="myform" method="get">
- You have to use [Formspree](https://formspree.io/) for you contact form submission action.
  - You can check the project's requirements and the documentation of the formspree for more details.

2024-07-29 19:27 UTC, ahzamir commented on script.js
> +  const emailChecker = /^[\w-]+@[a-zA-Z\d-]+\.[a-zA-Z]{2,}$/;
- You have to check if the user writes his email in capital or small letters and if it has any capital letters you have to show an error message:
  - Check the project requirements for more details.

2024-07-29 19:27 UTC, ahzamir commented on README.md
> +- You can give some information about me.
- Solve this, as the user does not give information about you they will read info about you.

2024-07-29 19:27 UTC, ahzamir commented on README.md
> +```
- You can remove this part.

2024-07-29 19:27 UTC, ahzamir commented on README.md
> +![Demo](/images/DEMO.png)
- The demo image is not showing up as your image is `Demo.png` not `DEMO.png`

2024-07-29 19:27 UTC, ahzamir commented on README.md
> +[The_live_link_of_this_project](https://najeeba-qarqin.github.io/Portfolio-JS/)
- This link is not working, but no worries you can update it after you deployed this project

2024-07-29 19:27 UTC, ahzamir commented on README.md
> +
- Change this to Technologies and Tools used and then also add Figma on the below list

2024-07-29 19:27 UTC, ahzamir commented on README.md
> +  ####  Farkhunda Raufi
- Add a link to the Figma design here and also you need to add at least one social media link for these UI/UX designers.

2024-07-30 14:47 UTC, Najeeba-Qarqin commented
> @Najeeba-Qarqin
> 
> * Well done Najeeba, your project is almost done but has some minor issues first of all before I check your project design and functionality, I need to match it with the Figma design so please provide the link to the Figma design in reply to this message and also on your README.md file.

Hi sir thank you for feedback 
Ok this is the link: 
 https://www.figma.com/invites/claim/M4WghDpaGEamietPGHcEHoCfP4GsHkX0yXRl13g9J5TR?fuid=1379424393568974635

2024-07-30 14:51 UTC, Najeeba-Qarqin commented on README.md
> +```
Why sir, and how??🥺

2024-07-30 15:08 UTC, Najeeba-Qarqin commented on README.md
> +```
Understand 🙂

2024-07-31 05:56 UTC, Najeeba-Qarqin commented
@ahzamir Hi sir!
I implemented  your feedback can you please check the project again.

2024-07-31 18:37 UTC, ahzamir requested changes
@Najeeba-Qarqin 

- Well done Najeeba by implementing the feedback and creating this amazing project just some minor changes on the design of the project are remaining you need to work on:

2024-07-31 18:37 UTC, ahzamir commented on script.js
> +});
@Najeeba-Qarqin 

- Well done, just one thing else you need to implement here after the user submits the form you need to clear the Form fields inner text and the LocalStorage Data.

2024-07-31 18:37 UTC, ahzamir commented on styles.css
- The background color for the project pages including the project header is a linear gradient color, you have to use the exact linear gradient color on your project background, please have a look at the images to see the changes between your design and the Figma design:
- The buttons' background color also has little gradient and shadow on the Figma Design.
- The padding and sizing of the Elements on the Home page are a little bit different from the Figma design

- The Figma Design:
![image](https://github.com/user-attachments/assets/19ae6db0-c043-4e53-9b1f-801a7e27073a)
|
![image](https://github.com/user-attachments/assets/0a0518bf-c9b8-43fc-b921-c80956bbb122)


- Your Design:
  - Desktop version:
  - Here I added just the desktop version design as a reference but implement these changes for both desktop and mobile versions.
  
![image](https://github.com/user-attachments/assets/4f53470e-8169-4f77-9f0a-456dfca04ce5)
|
![image](https://github.com/user-attachments/assets/24965ab4-a0bf-4383-95f8-bfeb1e660afc)

2024-07-31 18:37 UTC, ahzamir commented on styles.css
- The placing od the button on the about page is different from the Figma design:
- Same issue on the About page, the button design and sizing are not aligned and the same as the Figma design:

- Your Design:
![image](https://github.com/user-attachments/assets/5a7f6974-fae6-4935-8578-d1177bd7c9b3)

![image](https://github.com/user-attachments/assets/96df1114-31f5-4c3a-a78d-40393b0a7cb0)

- The Figma Design:
![image](https://github.com/user-attachments/assets/f1dc2bf9-90bb-4060-8445-f4dd53fa0fbc)
![image](https://github.com/user-attachments/assets/9aed580c-2889-4c6a-a57d-d4c1ad9b552e)

2024-07-31 18:37 UTC, ahzamir commented on styles.css
- Padding issue on the skills page, please check the Figma design and add padding to your elements according to the Figma Design:
- Also the text under skills should be centered

- Your Design Mobile version:
![image](https://github.com/user-attachments/assets/9a090a67-2d41-4bc0-9721-c2a0843c75f2)

- Figma Design:
![image](https://github.com/user-attachments/assets/8a2c95c7-02f3-4744-8044-1f0f368c86e4)

2024-07-31 18:37 UTC, ahzamir commented on styles.css
@Najeeba-Qarqin 

- Although I accept that the changes you added is looking more professional and more cool on your project, but as this project is a lesson for you to follow the exact design which is on the Figma so you need to design exactly like the Figma Design:
- No background for the projects card:

- Your design:
![image](https://github.com/user-attachments/assets/3f5751d0-68bf-4dd9-864f-b7b3cab50b1a)

- Figma Design:
![image](https://github.com/user-attachments/assets/fa770660-220b-4f95-83cc-0304f5d8cc48)

2024-07-31 18:37 UTC, ahzamir commented on styles.css
- These button icons imported with a very low format graphic although it's correct on the Figma solve this:
![image](https://github.com/user-attachments/assets/02d29d4e-a592-4a6a-8b8a-1f021a136032)

2024-07-31 21:29 UTC, Najeeba-Qarqin commented on styles.css
> * The background color for the project pages including the project header is a linear gradient color, you have to use the exact linear gradient color on your project background, please have a look at the images to see the changes between your design and the Figma design:
> * The buttons' background color also has little gradient and shadow on the Figma Design.
> * The padding and sizing of the Elements on the Home page are a little bit different from the Figma design
> * The Figma Design:
>   ![image](https://private-user-images.githubusercontent.com/96838030/353931129-19ae6db0-c043-4e53-9b1f-801a7e27073a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NTkxMzcsIm5iZiI6MTcyMjQ1ODgzNywicGF0aCI6Ii85NjgzODAzMC8zNTM5MzExMjktMTlhZTZkYjAtYzA0My00ZTUzLTliMWYtODAxYTdlMjcwNzNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIwNDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiNjQzMTQxYmM5ZTQ0OWFhMDI2NTEwOTAxMGNlZjBiNjdhMzcxNGI5YzVlMThmN2ZiYjFkZDg0MWYyOGQ0YmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1jq7C_ZESZNsnrgNPbl1iv8Dwd4_V_BuG3o78NJ7P_A)
>   |
>   ![image](https://private-user-images.githubusercontent.com/96838030/353932378-0a0518bf-c9b8-43fc-b921-c80956bbb122.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NTkxMzcsIm5iZiI6MTcyMjQ1ODgzNywicGF0aCI6Ii85NjgzODAzMC8zNTM5MzIzNzgtMGEwNTE4YmYtYzliOC00M2ZjLWI5MjEtYzgwOTU2YmJiMTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIwNDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkOThiZTZkZmYzNzBhZDgwNTI1NTM4MTI3YjZkYWVlNzZkNmM0MWE2N2I5MGRlZjY1MWRkYmQ1MjAyYWUzN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M4Imu6r8BG3XQbPxMysNxdzFnBGUEbXpRkV1_f2x6bk)
> * Your Design:
>   
>   * Desktop version:
>   * Here I added just the desktop version design as a reference but implement these changes for both desktop and mobile versions.
> 
> ![image](https://private-user-images.githubusercontent.com/96838030/353933085-4f53470e-8169-4f77-9f0a-456dfca04ce5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NTkxMzcsIm5iZiI6MTcyMjQ1ODgzNywicGF0aCI6Ii85NjgzODAzMC8zNTM5MzMwODUtNGY1MzQ3MGUtODE2OS00Zjc3LTlmMGEtNDU2ZGZjYTA0Y2U1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIwNDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZjExOWI4NTBhNzdhYzBjODc3Mzg4YjA0ZDQyZGVjMjI0N2NmMjI1OGE2ZjlmODY0ZDEzN2Q4Mzc2YmM0NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wqWigpA1kpS9oI1rtRANCex3d5BEVzXkpiNVuBPKirs) | ![image](https://private-user-images.githubusercontent.com/96838030/353932217-24965ab4-a0bf-4383-95f8-bfeb1e660afc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NTkxMzcsIm5iZiI6MTcyMjQ1ODgzNywicGF0aCI6Ii85NjgzODAzMC8zNTM5MzIyMTctMjQ5NjVhYjQtYTBiZi00MzgzLTk1ZjgtYmZlYjFlNjYwYWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDIwNDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkZjllZDA1MTVkYjc4ODNjYzdkOGI3NWY4MTczODZjYmNhNWYzZDA3YzQ0ZGY0ZTliZDYzMTZiYmFhMTk3NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Fbd92tXnd2o57MjCXe80Wy3GXpfU66dsDdTYDWNsTSg)

the linear gradient color is for it's border sir not for background i looked at it have only one color for background if i add the linear gradient it make sense like light color.

2024-07-31 22:39 UTC, Najeeba-Qarqin commented
@ahzamir Salam sir!
I changed the required points of design that you mentioned just about the background of the body please check again cause when i added linear gradient it makes big difference.

2024-08-01 12:28 UTC, ahzamir commented on styles.css
- From my point of view, I think the body background is a linear gradient consisting of 3 colors, check the Figma design there you can find which colors with which percentages!

2024-08-01 15:13 UTC, ahzamir commented
> @ahzamir Salam sir! I changed the required points of design that you mentioned just about the background of the body please check again cause when i added linear gradient it makes big difference.

I checked it, it's a linear gradient background.

2024-08-01 15:30 UTC, Najeeba-Qarqin commented
> > @ahzamir Salam sir! I changed the required points of design that you mentioned just about the background of the body please check again cause when i added linear gradient it makes big difference.
> 
> I checked it, it's a linear gradient background.

![Screenshot_20240801-195922_Chrome](https://github.com/user-attachments/assets/2eb6dac6-f7e8-4ffd-941f-39273431142f)
Sir can you explain please it's just one color for background 🥺

2024-08-03 20:31 UTC, Najeeba-Qarqin commented
@ahzamir 
Hi sir!
I added a radial gradient color for background of project.

2024-08-08 18:40 UTC, ahzamir approved these changes
### Hi @Najeeba-Qarqin 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/user-attachments/assets/13ae81e2-ff65-417d-ba1f-cdb7219e816a)

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![WinkThumbsUpGIF](https://github.com/ZohalMirkhel/palindrome/assets/96838030/e5ee293e-072a-4806-bde0-b64e13140efa)


 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)✔️ You have followed the Cash Register project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive
✔️Your design is according to the Figma design and even better than that. 🎯

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

2024-08-08 18:41 UTC, ahzamir commented
@Najeeba-Qarqin 

- Don't forget to:
  - Merge
  - Deploy
  - Share on FB Group & Social Media

> These are part of the requirments

2024-08-09 05:10 UTC, merged